#!/bin/bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $SCRIPT_DIR

echo -e "\033[32mStarting nubushmovienight setup in $(pwd)...\033[0m"
echo "This will required pipenv to already be installed!"

set -e

pipenv --three
pipenv install


echo -e "\033[33mLook for config\033[0m"

AUTO_CFG="$SCRIPT_DIR/current.config"
if [ "" == "$NBMN_CONFIG" ]; then
    if [ -f "$AUTO_CFG" ]; then
        echo "NBNM_CONFIG not defined, but found $AUTO_CFG"
        echo "Check that file for your configuration when running ./run or ./tools"
    else
        echo -e "\033[31mNOTE! NBMN_CONFIG is not defined and $AUTO_CFG does not exist\033[0m"
        echo "Only the default values in $SCRIPT_DIR/default.config will be used"
    fi
else
    echo "Found NBMN_CONFIG=$NBMN_CONFIG"
    echo "Check that file for your configuration when running ./run or ./tools"
fi

echo -e "\033[32mSetup Complete\033[0m"
